export const CURRENT_YEAR = new Date().getFullYear() - 1

export const TOPICS = {
  android: 'Polkaswap',
  cfml: 'Dock',
  clojure: 'Clojure',
  cpp: 'Shiden',
  css: 'Anyswap',
  data: 'Chainlink',
  devops: 'Kusama',
  dotnet: 'Clover Finance',
  elixir: 'Edgeware',
  elm: 'Elm',
  general: 'Polkadot',
  golang: 'Crust Network',
  graphql: 'Stafi',
  groovy: 'Groovy',
  ios: 'Litentry',
  iot: 'Sora Validator',
  java: 'Sushi',
  javascript: 'Moonriver',
  kotlin: 'Kotlin',
  leadership: 'Sora',
  networking: 'MathChain',
  php: 'Automata',
  product: 'Centrifuge',
  python: 'OriginTrail',
  ruby: 'Solarbeam',
  rust: 'ChainX',
  scala: 'Scala',
  security: 'Reef Finance',
  testing: 'Karura',
  typescript: 'TypeScript',
  'tech-comm': 'Content strategy',
  ux: 'Phala Network',
}
